openapi: "3.0.0"
info:
  title: TODO API Documentation
  version: "0.0.1"
  description: This is doc for ToDO-API
paths:
  /health:
    get:
      responses:
        '200':
          description: OK - The API is healthy
